name: Release new version of examples pass

on:
  push:
    branches: [acc]

jobs:
  test_and_release:
    concurrency:
      group: "acc"
      cancel-in-progress: false
    secrets: inherit
    uses: guidion-digital/terrappy/.github/workflows/tf-module-releaser.yaml@CI-630
    permissions:
      contents: write
    with:
      source_dirs: '["examples/test_app"]'
